
# PARTE 1 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR LA EXTRACCION Y PREPROCESO DE LA BASE DE LOS PRECIOS, 
# SEGUN EL DICCIONARIO DE TICKETS DISPONIBILIZADO QUE CONTIENE TODAS LAS TENENCIAS DISPONIBLES EN LAS CARTERAS
# PARA EVITAR ERRORES SE REALIZARA EN BATCH DE A 25 TICKERS POR CONSULTA, TOMANDO UNA SERIE DE LOS ULTIMOS 10 DIAS
# PARA LUEGO OBTENER EL PRECIO ULTIMO
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM


library(readxl)
library(purrr)
library(tidyquant)
library(dplyr)


source("FUNCTIONS/YFINANCE_BATCH.R")


# CARGA DICCIONARIO

DICCIONARIO_TICKERS<-read_excel("FILES/INPUTS/DICCIONARIO_TICKERS.xlsx")

# OBTENER EL LISTADO DE TICKERS DEL DICCIONARIO

TICKERS<-DICCIONARIO_TICKERS%>%distinct(NEMO)%>%pull(NEMO)

# OBTENGO EN BATCHES DE 25 TODOS LOS PRECIOS DE LAS ACCIONES DE LOS ULTIMOS 10 DIAS

ULTIMOS_PRECIOS <- tq_get_batch(TICKERS=TICKERS,from=Sys.Date()-10,batch_size=25,sleep_sec  = 5)

# OBTENGO EL ULTIMO PRECIOA AJUSTADO DISPONIBLE UTILIZANDO SLICE_MAX, CAMBIANDO LOS NOMBRES DE LOS CAMPOS

ULTIMO_PRECIO_AJUSTADO<-ULTIMOS_PRECIOS%>%group_by(symbol)%>%
  slice_max(date, n = 1, with_ties = FALSE)%>%ungroup() %>%
  transmute(NEMO = symbol,PRECIO_ULT = adjusted)

# CRUZO NEMOTECNICOS CON DICCIONARIO

DICCIONARIO_TICKERS<-DICCIONARIO_TICKERS%>%left_join(ULTIMO_PRECIO_AJUSTADO,by="NEMO")

# EXPORTO LA TABLA DE LOS ULTIMOS PRECIOS DE LAS ACCIONES QUE SE OCUPARAN

write.table(DICCIONARIO_TICKERS, file = "FILES/INTERMEDIO/01_PRECIOS_ACCIONES.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)

