
# PARTE 1 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR LA EXTRACCION Y PREPROCESO DE LA BASE DE LOS PRECIOS, 
# SEGUN EL DICCIONARIO DE TICKETS DISPONIBILIZADO QUE CONTIENE TODAS LAS TENENCIAS DISPONIBLES EN LAS CARTERAS
# PARA EVITAR ERRORES SE REALIZARA EN BATCH DE A 25 TICKERS POR CONSULTA, TOMANDO UNA SERIE DE LOS ULTIMOS 10 DIAS
# PARA LUEGO OBTENER EL PRECIO ULTIMO
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM


library(readxl)
library(purrr)
library(tidyquant)
library(dplyr)


source("FUNCTIONS/YFINANCE_BATCH.R")


# CARGA DICCIONARIO

DICCIONARIO_TICKERS<-read_excel("FILES/INPUTS/DICCIONARIO_TICKERS.xlsx")

# OBTENER EL LISTADO DE TICKERS DEL DICCIONARIO

TICKERS<-DICCIONARIO_TICKERS%>%distinct(NEMO)%>%pull(NEMO)

# OBTENGO EN BATCHES DE 25 TODOS LOS PRECIOS DE LAS ACCIONES DE LOS ULTIMOS 10 DIAS

ULTIMOS_PRECIOS <- tq_get_batch(TICKERS=TICKERS,from=Sys.Date()-10,batch_size=25,sleep_sec  = 5)

# REVISAR TICKETS EXTRAIDOS

tickers_extraidos <- unique(ULTIMOS_PRECIOS$symbol)

# REVISAR TICKETS TIME OUT

tickers_faltantes <- setdiff(TICKERS, tickers_extraidos)

# RECUPERAR TICKETS FALTANTES

if (length(tickers_faltantes) > 0) {

  PRECIOS_REINTENTO <- tq_get_batch(
    TICKERS   = tickers_faltantes,
    from      = Sys.Date() - 10,
    batch_size = 5,
    sleep_sec  = 15
  )

} else {
  PRECIOS_REINTENTO <- NULL
}

# TABLA TOTAL DE TICKETS CORREGIDA

PRECIOS_HISTORICOS_FINAL <- bind_rows(
  ULTIMOS_PRECIOS,
  PRECIOS_REINTENTO
) %>%
  distinct(symbol, date, .keep_all = TRUE)


# OBTENGO EL ULTIMO PRECIO AJUSTADO DISPONIBLE UTILIZANDO SLICE_MAX, CAMBIANDO LOS NOMBRES DE LOS CAMPOS

ULTIMO_PRECIO_AJUSTADO<-ULTIMOS_PRECIOS%>%group_by(symbol)%>%
  slice_max(date, n = 1, with_ties = FALSE)%>%ungroup() %>%
  transmute(NEMO = symbol,PRECIO_ULT = adjusted)

# CRUZO NEMOTECNICOS CON DICCIONARIO

DICCIONARIO_TICKERS<-DICCIONARIO_TICKERS%>%left_join(ULTIMO_PRECIO_AJUSTADO,by="NEMO")

# EXPORTO LA TABLA DE LOS ULTIMOS PRECIOS DE LAS ACCIONES QUE SE OCUPARAN

write.table(DICCIONARIO_TICKERS, file = "FILES/INTERMEDIO/01_PRECIOS_ACCIONES.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)

