
# PARTE 2 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR EL CRUCE ENTRE LA TABLA DE TENENCIA Y LA BASE DEL MANTENEDOR
# DE EJECUTIVOS POR CUENTA

# TIEMPO ESTIMADO DE EJECUCION: INSTANTANEO

# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM


library(readr)
library(dplyr)
library(tidyquant)


# CARGA DE ARCHIVO CRM DE TENENCIA

TBL_DATA_SHARES_ACCOUNTS <- read_csv2("FILES/INPUTS/TBL_DATA_SHARES_ACCOUNTS.csv")
TBL_FM_DAP_ACCOUNTS <- read.csv2("FILES/INPUTS/TBL_ACCOUNTS_DAP_FM_VIGENTE.csv")
TBL_ACCOUNT_MANAGER <- read_csv2("FILES/INPUTS/TBL_ACCOUNT_MANAGER.csv")



# CRUCE TABLA SHARES PARA OBTENER EJECUTIVO ASIGNADO


TBL_DATA_SHARES_ACCOUNTS<-TBL_DATA_SHARES_ACCOUNTS%>%left_join(TBL_ACCOUNT_MANAGER, by=c("ID_CLIENTE"="IDACCOUNT"))

TBL_FM_DAP_ACCOUNTS<-TBL_FM_DAP_ACCOUNTS%>%left_join(TBL_ACCOUNT_MANAGER, by=c("ID_CLIENTE"="IDACCOUNT"))




write.table(TBL_DATA_SHARES_ACCOUNTS, file = "FILES/INTERMEDIO/02_BASE_CUSTODIA_PRINCIPAL.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)

write.table(TBL_FM_DAP_ACCOUNTS, file = "FILES/INTERMEDIO/02_BASE_CUSTODIA_DAP_FM_PRINCIPAL.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)



