
# PARTE 3 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR EL PROCESAMIENTO DE LA BASE DE PREFERENCIAS DE LA ENCUESTA
# LA INFORMACION DE LAS PREFERENCIAS QUE VIENEN DE LA BASE DE LA WEB
# Y PREPROCESO DE LA BASE DONDE SE OBTIENEN LOS RESULTADOS DE LOS ULTIMOS 12 MESES
# SE DEJAN VALORES DE NEMOTECNICOS UNICOS SELECCIONADOS POR EL CLIENTE EN LOS ULTIMOS 12 MESES
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM

library(readxl)
library(dplyr)
library(tidyr)
library(lubridate)

#CARGA TABLAS

PREF_SATISFACCION<-read_excel("FILES/INPUTS/RESULTADOS_ENCUESTA_ACUMULADO_MODELO_NPS.xlsx")
PREF_WEB <- read_csv2("FILES/INPUTS/TBL_CUS_PREFERENCIAS_DECLARADAS_UNICAS.CSV")
DICCIONARIO_TICKERS<-read_excel("FILES/INPUTS/DICCIONARIO_TICKERS.xlsx")

# SEPARO BASE NPS


NPS<-PREF_SATISFACCION%>%select(ID_CLIENTE,AÑOMES_ENCUESTA,FECHA_ENCUESTA,NPS)

# ORDENO DE MAYOR A MENOR LA ULTIMA ENCUESTA NPS DISPONIBLE

NPS<-NPS %>%arrange(ID_CLIENTE, desc(FECHA_ENCUESTA)) %>%
  distinct(ID_CLIENTE, .keep_all = TRUE)

# ORDENO DE MAYOR A MENOR POR LA ULTIMA ENCUESTA DE SATISFACCION CON LAS PREFERENCIAS

PREF_SATISFACCION<-PREF_SATISFACCION %>%arrange(ID_CLIENTE, desc(FECHA_ENCUESTA)) %>%
  distinct(ID_CLIENTE, .keep_all = TRUE)

# BUSCO LA ULTIMA ENCUESTA DISPONIBLE

FECHA_CORTE<-max(PREF_SATISFACCION$FECHA_ENCUESTA, na.rm = TRUE)

# DESDE LA FECHA DE CORTE FILTRO POR LOS ULTIMOS 12 MESES

PREF_SATISFACCION<-PREF_SATISFACCION %>%
  filter(FECHA_ENCUESTA>=FECHA_CORTE %m-% months(12))


# SEPARO LA LISTA DE LAS PREFERENCIAS DE LA ENCUESTA DE SATISFACCION

PREF_SATISFACCION_LARGO<-PREF_SATISFACCION %>%
  separate_rows(ID_PREF, sep = ";")

# CRUZO EL ID DE LA EMPRESA DEL DICCIONARIO CON EL ID DE LAS PREFERENCIAS PARA OBTENER EL NEMOTECNICO

PREF_SATISFACCION_LARGO<-PREF_SATISFACCION_LARGO%>%left_join(DICCIONARIO_TICKERS, by=c("ID_PREF"="ID_EMPRESA"))


# ORDENO POR FECHA DE MAS RECIENTE A MAS ANTIGUO LAS PREFERENCIAS DE LA WEB

PREF_WEB <- PREF_WEB %>%
  arrange(ID_CLIENTE, desc(FECHA_ENCUESTA)) %>%
  distinct(ID_CLIENTE, .keep_all = TRUE)

# OBTENGO LA MAXIMA FECHA DE CORTE DE LA ENCUESTA

FECHA_CORTE <-
  max(PREF_WEB$FECHA_ENCUESTA, na.rm = TRUE)

# TOMO LOS ULTIMOS 12 MESES DESDE LA FECHA DE CORTE

PREF_WEB <-PREF_WEB %>%
  filter(FECHA_ENCUESTA >= FECHA_CORTE %m-% months(12))

# SEPARACION DE LA LISTA DE PREFERENCIAS DE LA WEB

PREF_WEB_LARGO <-PREF_WEB %>%
  separate_rows(ID_PREFERENCIAS, sep = ";")

# CAMBIO DE NOMBRE DE VARIABLE DEL ID DE LA PREFERENCIA ID_PREFERENCIAS POR ID_PREF

names(PREF_WEB_LARGO)[4]<-"ID_PREF"

# CRUCE LISTADO WEB LARGO CON DICCIONARIO TICKERS

PREF_WEB_LARGO<-PREF_WEB_LARGO%>%left_join(DICCIONARIO_TICKERS, by=c("ID_PREF"="ID_EMPRESA"))

# SELECCIONAR CAMPOS DEL ID Y NEMOTECNICO DE PREFERENCIA

PREF_WEB_LARGO<-PREF_WEB_LARGO%>%select(ID_CLIENTE,NEMO)
PREF_SATISFACCION_LARGO<-PREF_SATISFACCION_LARGO%>%select(ID_CLIENTE,NEMO)

# CONCATENACION DE TABLAS DE SATISFACCION Y LA WEB

PREF_TOTALES<-rbind(PREF_SATISFACCION_LARGO,PREF_WEB_LARGO)

# DEJAR VALORES DISTINTOS EN LA TABLA FINAL

PREF_TOTALES <- PREF_TOTALES %>%
  distinct(ID_CLIENTE, NEMO)



write.table(PREF_TOTALES, file = "FILES/INTERMEDIO/03_PREFERENCIAS_ACCIONES_CLIENTES.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)


write.table(NPS, file = "FILES/INTERMEDIO/03_NPS_CLIENTES_ACUMULADO.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)

