
# PARTE 4 DEL RECOMENDADOR DE CARTERAS:

# ESTA PARTE PERMITE REALIZAR EL CRUCE ENTRE LA TABLA DE TENENCIA Y EL CALCULO DEL ULTIMO PRECIO DE LA ACCION
# SE EXTRAE EL ULTIMO PRECIO DISPONIBLE PARA LA ACCION EN CUSTODIA Y SE PEGA A LA BASE PRINCIPAL
# LA ACCION EXTRANJERA SE TRANSFORMA DE DOLAR A PESO
# SE CALCULA EL MONTO TOTAL EN CUSTODIA APROXIMADO
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM


library(readr)
library(dplyr)
library(tidyquant)


# CARGA DE ARCHIVO CRM DE TENENCIA

PRECIOS_ACCIONES<-read_csv2("FILES/INTERMEDIO/01_PRECIOS_ACCIONES.CSV")
BASE_CUSTODIA<-read_csv2("FILES/INTERMEDIO/02_BASE_CUSTODIA_PRINCIPAL.CSV")


# ULTIMO TIPO DE CAMBIO USD=>CLP


USD_CLP<-tq_get("USDCLP=X",from=Sys.Date()-4)%>%tail(1)%>% pull(adjusted)

USD_CLP <- ifelse(is.na(USD_CLP), 873.36, USD_CLP)


# CRUCE TABLA SHARES PARA OBTENER EJECUTIVO ASIGNADO


BASE_CUSTODIA<-BASE_CUSTODIA%>%left_join(PRECIOS_ACCIONES, by="ID_EMPRESA")



# EXTRANJERAS DE DOLAR A PESO

BASE_CUSTODIA<-BASE_CUSTODIA%>%mutate(PRECIO_ULT=ifelse(CATEGORIA=="EXTRANJERA",
                                                           PRECIO_ULT*USD_CLP,PRECIO_ULT))


# CALCULO DEL MONTO EN CUSTODIA TOTAL EN PESOS

BASE_CUSTODIA<-BASE_CUSTODIA%>%mutate(MONTO_EN_CUSTODIA=trunc(CANTIDAD_EN_CUSTODIA*PRECIO_ULT))

# EXPORT BASE MONTOS

write.table(BASE_CUSTODIA, file = "FILES/INTERMEDIO/04_MONTOS_EN_CUSTODIA.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)



