
# PARTE 6 DEL RECOMENDADOR DE CARTERAS (CARTERA ACTUAL + PREFERENCIAS):

# ESTA PARTE CONTIENE EL MODELO OPTIMIZADOR DE LA CARTERA EL CUAL RECORRE TODA LA BASE INCLUYENDO PREFERENCIAS
# DE CLIENTES Y SUS CUENTAS, CALCULANDO EL % OPTIMO SEGUN LA MAXIMIZACION DEL RATIO SHARPE
# CON ESTO SE OBTIENEN LOS PESOS OPTIMOS SEGUN LA CARTERA ACTUAL Y  LAS PREFERENCIAS DEL ULTIMO AÑO
# ADEMAS SE OBTIENEN INDICADORES FINANCIEROS RESPECTO A LA CARTERA OPTIMIZADA: 
# RETORNO, DESVIACION ESTANDAR, SHARPE POR CARTERA (ANUAL, MENSUAL, DIARIO)
# ADEMAS SE DETERMINA EL GAP ENTRE LA CARTERA ACTUAL, EL RETORNO, LA DESVIACION ESTANDAR Y LA TENENCIA ACTUAL
# SE DETERMINA CUANTO DEBE COMPRAR O VENDER O MANTENER DE UNA ACCION EN ESPECIFICO 
# ADEMAS SE INDICA SI DEBE APORTAR UN MOMNTO ADICIONAL PARA CUADRAR LA RECOMENDACION
# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM

library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(tidyquant)
library(nloptr)
library(writexl)
library(tibble)

TBL_DATA_SHARES_ACCOUNTS_FINAL<-read_csv2("FILES/INTERMEDIO/05_PESOS_INDICADORES_CARTERA.CSV")
PREF_TOTALES <- read_csv2("FILES/INTERMEDIO/03_PREFERENCIAS_ACCIONES_CLIENTES.CSV")
PRECIOS_HISTORICOS <- read_csv2("FILES/INTERMEDIO/05_PRECIOS_ACCIONES_TOTAL.CSV")
DICCIONARIO_TICKERS<-read_excel("FILES/INPUTS/DICCIONARIO_TICKERS.xlsx")
PRECIOS_ACCIONES<-read_csv2("FILES/INTERMEDIO/01_PRECIOS_ACCIONES.CSV")


# TASA LIBRE DE RIESGO PARA SHARPE

rf <- 0.03
rf_diario = rf / 252
rf_mensual = rf / 12




# ULTIMO TIPO DE CAMBIO USD=>CLP EN CASO DE NO HABER VALORES EN YFINANCE INGRESAR EL MONTO 

USD_CLP<-tq_get("USDCLP=X",from=Sys.Date()-4)%>%tail(1)%>% pull(adjusted)

# INGRESAR MONTO TIPO DE CAMBIO EN CASO DE ERROR EN YFINANCE

USD_CLP <- ifelse(is.na(USD_CLP), 873.36, USD_CLP)

# CONVERSION DEL PRECIO DE LA ACCION EXTRANJERA DE DOLAR A PESOS

PRECIOS_ACCIONES<-PRECIOS_ACCIONES%>%mutate(PRECIO_ULT=ifelse(CATEGORY=="EXTRANJERA",
                                                        PRECIO_ULT*USD_CLP,PRECIO_ULT))

# SELECCIONAR SOLO COLUMNAS NECESARIA DE LA TABLA PRECIO ACCIONES

PRECIOS_ACCIONES<-PRECIOS_ACCIONES%>%select(NEMO,NAME,PRECIO_ULT)

# INICIALIZAR CON 0 VALORES CLAVE PARA LA TABLA QUE CONTIENE LAS PREFERENCIAS TOTALES

PREF_TOTALES$PESO<-0
PREF_TOTALES$MONTO_EN_CUSTODIA<-0
PREF_TOTALES$CANTIDAD_EN_CUSTODIA<-0

# SELECCIONO COLUMNAS UTILES DE LA BASE DE CARTERA Y TENENCIA DE ACCIONES PARA COMPLEMENTAR LA BASE DE PREFERENCIAS Y LO DEJO UNICO SEEGUN ID_CUENTA

CUENTAS_DATOS<-TBL_DATA_SHARES_ACCOUNTS_FINAL%>%select(ID_CLIENTE,ID_CUENTA,USERNAME,
                                                       NOMBRE_EJECUTIVO,EQUIPO,JEFE_AREA,
                                                       RET_PROM_DIARIO,DE_DIARIA,RET_PROM_MENSUAL,
                                                       DE_MENSUAL,RET_PROM_ANUAL,DE_ANUAL,
                                                       SHARPE_DIARIO,SHARPE_MENSUAL,SHARPE_ANUAL)%>%unique()



# CALCULO DE LAS ACCIONES: RETORNO DIARIO, DESVIACION ESTANDAR DIARIA

METRICAS_ACCION <- PRECIOS_HISTORICOS %>%
  group_by(NEMO) %>%
  tq_transmute(
    select     = PRECIO,
    mutate_fun = periodReturn,
    period     = "daily",
    col_rename = "RET_DIARIO") %>%
  summarise(
    RET_PROM_DIARIO = mean(RET_DIARIO, na.rm = TRUE),
    DE_DIARIA       = sd(RET_DIARIO, na.rm = TRUE),
    .groups = "drop")


# CRUCE INFORMACION DE LAS CUENTAS CON LA BASE DE PREFERENCIAS

PREF_TOTALES<-PREF_TOTALES%>%left_join(CUENTAS_DATOS,by="ID_CLIENTE")

# DEJO EL ID DE LA CUENTA DESPUES DEL ID DEL CLIENTE

PREF_TOTALES <- PREF_TOTALES %>%
  relocate(ID_CUENTA, .after = ID_CLIENTE)

# DE LA TABLA DE CARTERAS Y TENENCIAS SELECCIONO ALGUNAS COLUMNAS RELEVANTES PARA ESTE SCRIPT

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  select(ID_CLIENTE, ID_CUENTA, NEMO, PESO, MONTO_EN_CUSTODIA, CANTIDAD_EN_CUSTODIA,
         USERNAME, NOMBRE_EJECUTIVO, EQUIPO, JEFE_AREA, RET_PROM_DIARIO, DE_DIARIA,
         RET_PROM_MENSUAL, DE_MENSUAL, RET_PROM_ANUAL, DE_ANUAL,
         SHARPE_DIARIO, SHARPE_MENSUAL, SHARPE_ANUAL)

# JUNTO LA BASE DE TENENCIA ACTUAL CON LA BASE DE PREFERENCIAS

TBL_DATA_SHARES_ACCOUNTS_FINAL <- bind_rows(TBL_DATA_SHARES_ACCOUNTS_FINAL,
  PREF_TOTALES)

# ELIMINO AQUELLAS PREFERENCIAS REPETIDAS DETECTANDOLAS COMO PESO = 0 (SIN TENENCIA = PREFERENCIA)

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  group_by(ID_CLIENTE, ID_CUENTA, NEMO) %>%
  filter(PESO != 0 | all(PESO == 0)) %>%
  ungroup()


# PREPARO LA TABLA PARA LA OPTIMIZACION

UNIVERSO_OPTIMIZACION<-TBL_DATA_SHARES_ACCOUNTS_FINAL%>%select("ID_CLIENTE","ID_CUENTA",
                                                                 "NEMO","PESO")

# AGREGO A TABLA OPTIMIZACION: RETORNOS Y DESVIACION ESTANDAR POR ACCION


UNIVERSO_OPTIMIZACION <- UNIVERSO_OPTIMIZACION %>%
  left_join(
    METRICAS_ACCION,
    by = "NEMO"
  )

# CALCULO LOS RETORNOS DIARIOS DE LAS ACCIONES USANDO LOGARITMO

RETORNOS_HISTORICOS <- PRECIOS_HISTORICOS %>%
  arrange(NEMO, FECHA) %>%
  group_by(NEMO) %>%
  mutate(
    RET_DIARIO = log(PRECIO / lag(PRECIO))
  ) %>%
  ungroup()

# PIVOTEO LA TABLA PARA DEJAR EN FILA LAS FECHAS Y EN COLUMNAS LOS RETORNOS DE LAS ACCIONES

RETORNOS_HISTORICOS_PIVOT <- RETORNOS_HISTORICOS %>%
  select(FECHA, NEMO, RET_DIARIO) %>%
  pivot_wider(names_from = NEMO, values_from = RET_DIARIO)


# ACTIVAR SI HAY QUE REALIZAR DEBUG


# CUENTAS_MUESTRA <- UNIVERSO_OPTIMIZACION %>%
#    distinct(ID_CUENTA) %>%
#    slice_sample(n = 100) %>%
#    pull(ID_CUENTA)
#  
# UNIVERSO_MUESTRA <- UNIVERSO_OPTIMIZACION %>%
#    filter(ID_CUENTA %in% CUENTAS_MUESTRA)

# EXTRAIGO LOS ID DE LAS CUENTAS QUE SE PROCESARAN EN EL OPTIMIZADOR

CUENTAS <- UNIVERSO_OPTIMIZACION %>%
  distinct(ID_CUENTA) %>%
  pull(ID_CUENTA)


# INICIALIZO LISTAS PARA INGRESAR LOS RESULTADOS DE PESOS Y RESUMEN TOMANDO EN CONSIDERACION EL Q DE CUENTAS


RESULTADOS_PESOS <- vector("list", length(CUENTAS))
RESULTADOS_RESUMEN <- vector("list", length(CUENTAS))

# || MODELO OPTIMIZADOR DE CARTERAS PARA LA BASE COMPLETA ||

# PARA LA CUENTA I DENTRO DE LA LISTA CUENTAS

for (i in seq_along(CUENTAS)) {
  
  # IDENTIFICO LA CUENTA ESPECIFICA
  
  id_cuenta <- CUENTAS[i]
  
  # MENSAJE LOG DE ESTADO REVISION DE CUENTA
  
  message("Optimizando ", i, " / ", length(CUENTAS), " -> ", id_cuenta)
  
  # PROMEDIO POR ACTIVO INDICAR TABLA PRINCIPAL DONDE SE ENCUENTRA LAS CARTERAS A OPTIMIZAR
  uni <- UNIVERSO_OPTIMIZACION %>%
    filter(ID_CUENTA == id_cuenta) %>%
    distinct(NEMO, .keep_all = TRUE) %>%
    select(NEMO, RET_PROM_DIARIO)
  
  nemos <- uni$NEMO
  mu <- as.numeric(uni$RET_PROM_DIARIO)
  names(mu) <- nemos
  
  n <- length(mu)
  if (n < 2) next
  
  # SUMATORIA DESDE RETORNOS HISTORICOS
  R_c <- RETORNOS_HISTORICOS_PIVOT %>%
    select(all_of(c("FECHA", nemos))) %>%
    select(-FECHA) %>%
    as.matrix()
  
  # CALCULO DE LA COVARIANZA
  
  Sigma <- cov(R_c, use = "pairwise.complete.obs")
  
  # AJUSTE DE ESTABILIZACION MINIMA  DEL VALOR DE LA MATRIZ DE COVARIANZAS
  Sigma <- Sigma + diag(1e-10, n)
  
  # OPTIMIZACION DEL SHARPE
  
  sharpe_neg <- function(w) {
    ret <- sum(w * mu)
    vol2 <- drop(t(w) %*% Sigma %*% w)
    if (!is.finite(vol2) || vol2 <= 1e-12) return(1e6)
    - (ret - rf_diario) / sqrt(vol2)
  }
  
  res <- nloptr(
    x0 = rep(1 / n, n),
    eval_f = sharpe_neg,
    eval_g_eq = function(w) sum(w) - 1,
    lb = rep(0, n),
    ub = rep(1, n),
    opts = list(
      algorithm = "NLOPT_LN_COBYLA",
      #MAXIMA CANTIDAD DE EVALUACIONES
      maxeval   = 3000
    )
  )
  
  w_opt <- as.numeric(res$solution)
  names(w_opt) <- nemos
  
  # OBTENER TABLA DE PESOS
  RESULTADOS_PESOS[[i]] <- tibble(
    ID_CUENTA = id_cuenta,
    NEMO      = nemos,
    PESO_OPT_PREF  = w_opt
  )
  
  # OBTENER VALORES PARA TABLA DE METRICAS
  ret_opt <- sum(w_opt * mu)
  desvest_opt <- sqrt(drop(t(w_opt) %*% Sigma %*% w_opt))
  sharpe_opt <- (ret_opt - rf) / desvest_opt
  
  # CALCULO DE METRICAS Y CREACION DE TABLA
  
  RESULTADOS_RESUMEN[[i]] <- tibble(
    ID_CUENTA = id_cuenta,
    RET_ESPERADO_DIARIO_OPTM_PREF = ret_opt,
    DESVEST_DIARIA_OPTM_PREF     = desvest_opt,
    SHARPE_DIARIO_OPTM_PREF      = sharpe_opt,
    RET_ESPERADO_MENSUAL_OPTM_PREF = ret_opt * 21,
    RET_ESPERADO_ANUAL_OPTM_PREF   = ret_opt * 252,
    DESVEST_MENSUAL_OPTM_PREF = desvest_opt * sqrt(21),
    DESVEST_ANUAL_OPTM_PREF   = desvest_opt * sqrt(252),
    SHARPE_MENSUAL_OPTM_PREF  = (ret_opt * 21) / (desvest_opt * sqrt(21)),
    SHARPE_ANUAL_OPTM_PREF    = (ret_opt * 252) / (desvest_opt * sqrt(252)),
    MSG_PREF = res$message
  )}


# CONCATENACION DE LOS PESOS OPTIMOS Y EL RESUMEN POR CADA UNA DE LAS CUENTAS

TABLA_PESOS_OPTM <- bind_rows(RESULTADOS_PESOS)
TABLA_RESUMEN_OPTM <- bind_rows(RESULTADOS_RESUMEN)

# DETERMINO UN MINIMO TOTAL, SI SUPERA EL MINIMO EL PESO DE LA ACCION = 0

EPSILON <- 1e-6

# GENERO LA CONDICION PARA HACER = 0 AQUELLOS PESOS QUE SON MUY CERCANOS A 0 (EPSILON)


TABLA_PESOS_OPTM <- TABLA_PESOS_OPTM %>%
  mutate(
    PESO_OPT_PREF = if_else(abs(PESO_OPT_PREF) < EPSILON, 0, PESO_OPT_PREF)
  )


# AJUSTE PARA QUE LA SUMA DE LASS ACCIONES SEAN = 1


TABLA_PESOS_OPTM <- TABLA_PESOS_OPTM %>%
  group_by(ID_CUENTA) %>%
  mutate(
    PESO_OPT_PREF = PESO_OPT_PREF / sum(PESO_OPT_PREF)
  ) %>%
  ungroup()


# CRUCE DE LA TABLA DE CUENTAS Y TENENCIAS CON LA TABLA: DE PESOS OPTIMOS, TABLA DE INDICADORES RESUMEN


TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  left_join(TABLA_PESOS_OPTM,   by = c("ID_CUENTA", "NEMO")) %>%
  left_join(TABLA_RESUMEN_OPTM, by = "ID_CUENTA")

# CRUCE DEL PRECIO DE LAS ACCIONES EN CLP EN LA BASE DE LA TENENCIA Y CUENTAS

TBL_DATA_SHARES_ACCOUNTS_FINAL<-TBL_DATA_SHARES_ACCOUNTS_FINAL%>%left_join(PRECIOS_ACCIONES,by="NEMO")

# CALCULO DEL MONTO EN CUSTODIA TOTAL PARA LA CUENTA

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  group_by(ID_CUENTA) %>%
  mutate(MONTO_EN_CUSTODIA_TOTAL = sum(MONTO_EN_CUSTODIA, na.rm = TRUE)) %>%
  ungroup()


# CALCULO DEL MONTO EN CUSTODIA OPTIMO PARA LA ACCION SEGUN EL PESO OPTIMO

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  mutate(MONTO_EN_CUSTODIA_OPT = PESO_OPT_PREF * MONTO_EN_CUSTODIA_TOTAL)


# CALCULO DE LA CANTIDAD DE ACCIONES OPTIMAS A COMPRAR

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  mutate(
    # CANTIDADES EN CUSTODIA CON REDONDEO
    CANTIDAD_EN_CUSTODIA_OPT = round(MONTO_EN_CUSTODIA_OPT / PRECIO_ULT, 0),
    
    # APORTE ADICIONAR POR EFECTO DEL REDONDEO
    APORTE_ADICIONAL = pmax(0,(CANTIDAD_EN_CUSTODIA_OPT * PRECIO_ULT) - MONTO_EN_CUSTODIA_OPT))

# CALCULO DE GAPS POR INDICADORES Y ETIQUETAS CATEGORICAS

TBL_DATA_SHARES_ACCOUNTS_FINAL <- TBL_DATA_SHARES_ACCOUNTS_FINAL %>%
  mutate(
    # GAPs Diario
    GAP_RET_DIARIO     = RET_ESPERADO_DIARIO_OPTM_PREF - RET_PROM_DIARIO,
    GAP_DESV_DIARIA    = DESVEST_DIARIA_OPTM_PREF - DE_DIARIA,
    GAP_SHARPE_DIARIO  = SHARPE_DIARIO_OPTM_PREF - SHARPE_DIARIO,
    
    # GAPs Mensual
    GAP_RET_MENSUAL    = RET_ESPERADO_MENSUAL_OPTM_PREF - RET_PROM_MENSUAL,
    GAP_DESV_MENSUAL   = DESVEST_MENSUAL_OPTM_PREF - DE_MENSUAL,
    GAP_SHARPE_MENSUAL = SHARPE_MENSUAL_OPTM_PREF - SHARPE_MENSUAL,
    
    # GAPs Anual
    GAP_RET_ANUAL      = RET_ESPERADO_ANUAL_OPTM_PREF - RET_PROM_ANUAL,
    GAP_DESV_ANUAL     = DESVEST_ANUAL_OPTM_PREF - DE_ANUAL,
    GAP_SHARPE_ANUAL   = SHARPE_ANUAL_OPTM_PREF - SHARPE_ANUAL
  ) %>%
  mutate(
    FLAG_MEJORA_RIESGO_ANUAL   = ifelse(GAP_DESV_ANUAL < 0, "MEJORA", "EMPEORA"),
    FLAG_MEJORA_RETORNO_ANUAL = ifelse(GAP_RET_ANUAL > 0, "MEJORA", "EMPEORA"),
    
    # GAP de Cantidades en Custodia
    GAP_Q_CUSTODIA = CANTIDAD_EN_CUSTODIA_OPT - CANTIDAD_EN_CUSTODIA,
    
    FLAG_ACCION_Q = case_when(
      GAP_Q_CUSTODIA > 0 ~ "COMPRAR",
      GAP_Q_CUSTODIA < 0 ~ "VENDER",
      TRUE               ~ "MANTENER"
    )
  )





write.table(TBL_DATA_SHARES_ACCOUNTS_FINAL, file = "FILES/OUTPUT/06_TABLA_RESUMEN_FINAL_CON_PREFERENCIAS.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)







