
# PARTE 8 SISTEMA DE ALERTA TEMPRANA - CONCATENAR BASES:

# ESTA PARTE SE REALIZA LA CONCATENACION DE LOS RESULTADOS DE LOS MODELOS DE REDES NEURONALES
#NO EJECUTAR MENUALMENTE, ESTE CORRESPONDE AL SCRIPT DE ENTRENAMIENTO

#TIEMPO ESTIMADO DE EJECUCION: INSTANTANEO

# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM



library(readxl)

RED_NEURONAL_PATRIMONIAL_PREFERENTE <- read_excel(
  "FILES/OUTPUT/08_RED_NEURONAL_PATRIMONIAL_MENSUAL.xlsx"
)

RED_NEURONAL_RIESGOSO_TENSO <- read_excel(
  "FILES/OUTPUT/08_RED_NEURONAL_RIESGOSO_TENSO_MENSUAL.xlsx"
)


RED_NEURONAL_RIESGOSO_TENSO<-RED_NEURONAL_RIESGOSO_TENSO%>%select(ID_CLIENTE,PROB_CLUSTER13,PRED_CLUSTER13,PROB_CLUSTER13,TARGET13)


RED_NEURONAL_PATRIMONIAL_PREFERENTE<-RED_NEURONAL_PATRIMONIAL_PREFERENTE%>%inner_join(RED_NEURONAL_RIESGOSO_TENSO,by="ID_CLIENTE")

RED_NEURONAL_PATRIMONIAL_PREFERENTE <- RED_NEURONAL_PATRIMONIAL_PREFERENTE %>%
  mutate(
    ALERTA_CLUSTER_PATRIMONIAL = case_when(
      TARGET26PREF == 0 & PRED_CLUSTER26PREF == 1 ~ "Potencial Entrada Preferente",
      TARGET26PREF == 1 & PRED_CLUSTER26PREF == 0 ~ "Potencial Salida Preferente",
      TRUE ~ "NO"
    ),
    ALERTA_CLUSTER_CRITICO = case_when(
      TARGET13 == 0 & PRED_CLUSTER13 == 1 ~ "Potencial Entrada Critico/Tenso",
      TARGET13 == 1 & PRED_CLUSTER13 == 0 ~ "Potencial Salida Critico/Tenso",
      TRUE ~ "NO"
    )
  )

RED_NEURONAL_PATRIMONIAL_PREFERENTE <- RED_NEURONAL_PATRIMONIAL_PREFERENTE %>%
  mutate(
    CLUSTER = as.character(CLUSTER),
    CLUSTERNOMBRE = case_when(
      CLUSTER == "2" ~ "Diversificado Tenso",
      CLUSTER == "1" ~ "Accionario Preferente",
      CLUSTER == "4" ~ "Mixto Exigente",
      CLUSTER == "3" ~ "Accionario Tradicional",
      CLUSTER == "5" ~ "Accionario Tactico",
      CLUSTER == "6" ~ "Patrimonial Preferente",
      CLUSTER == "DAP" ~ "Conservador DAP/FM",
      CLUSTER == "DAP_PREFERENTE" ~ "Patrimonial DAP/FM",
      TRUE ~ NA_character_
    )
  )


RED_NEURONAL_PATRIMONIAL_PREFERENTE <- RED_NEURONAL_PATRIMONIAL_PREFERENTE %>%
  mutate(
    ALERTA_TEMPRANA_CLUSTER = case_when(
      ALERTA_CLUSTER_CRITICO != "NO" ~ ALERTA_CLUSTER_CRITICO,
      ALERTA_CLUSTER_CRITICO == "NO" & ALERTA_CLUSTER_PATRIMONIAL != "NO" ~ ALERTA_CLUSTER_PATRIMONIAL,
      TRUE ~ "NO"
    )
  )

write.table(RED_NEURONAL_PATRIMONIAL_PREFERENTE, file = "FILES/OUTPUT/08_TABLA_RESUMEN_FINAL_CON_SEGMENTO_RED_NEURONAL.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)





