
# PARTE 8 SISTEMA DE ALERTA TEMPRANA - RED NEURONAL PATRIMONIAL PREFERENTE:

# ESTA PARTE SE REALIZA LA CONCATENACION DE LOS RESULTADOS DE LOS MODELOS DE REDES NEURONALES
#NO EJECUTAR MENUALMENTE, ESTE CORRESPONDE AL SCRIPT DE ENTRENAMIENTO

#TIEMPO ESTIMADO DE EJECUCION: 1 A 2 MINUTOS

# CUALQUIER DUDA CONSULTAR AL AUTOR: 
# RODRIGO ESCOBAR LANDAETA | RESCOBARL@FEN.UCHILE.CL | LANDAETA77@GMAIL.COM



CLIENTE_SEGMENTO <- read_csv2("FILES/OUTPUT/08_TABLA_RESUMEN_FINAL_CON_SEGMENTO_RED_NEURONAL.CSV")

CON_PREFERENCIA <- read_csv2("FILES/OUTPUT/06_TABLA_RESUMEN_FINAL_CON_PREFERENCIAS.CSV")

SIN_PREFERENCIA <- read_csv2("FILES/OUTPUT/05_PESOS_INDICADORES_CARTERA.csv")

DAP_FM<-read.csv2("FILES/INTERMEDIO/02_BASE_CUSTODIA_DAP_FM_PRINCIPAL.CSV")


CLIENTE_SEGMENTO<-CLIENTE_SEGMENTO%>%
  select(ID_CLIENTE,
         Q_CUENTAS,
         Q_EMPRESAS_INVIERTE,
         CANTIDAD_EN_CUSTODIA_TOTAL,
         MONTO_TOTAL_ACCIONES,
         MONTO_TOTAL_DAP,
         MONTO_TOTAL_FM,
         RET_ANUAL_PONDERADO,
         DE_ANUAL_PONDERADO,
         SHARPE_ANUAL_PONDERADO,
         NPS,
         INTERACCIONES_NEGATIVAS_6M,
         INTERACCIONES_NEUTRAS_6M,
         INTERACCIONES_POSITIVAS_6M,
         CLUSTERNOMBRE,
         ALERTA_TEMPRANA_CLUSTER)

CLIENTE_SEGMENTO<-unique(CLIENTE_SEGMENTO)

CLIENTE_SEGMENTO$MONTO_TOTAL_CLIENTE<-CLIENTE_SEGMENTO$MONTO_TOTAL_ACCIONES+CLIENTE_SEGMENTO$MONTO_TOTAL_DAP+CLIENTE_SEGMENTO$MONTO_TOTAL_FM

CON_PREFERENCIA<-CON_PREFERENCIA%>%inner_join(CLIENTE_SEGMENTO,by="ID_CLIENTE")
SIN_PREFERENCIA<-SIN_PREFERENCIA%>%inner_join(CLIENTE_SEGMENTO,by="ID_CLIENTE")
DAP_FM<-DAP_FM%>%inner_join(CLIENTE_SEGMENTO,by="ID_CLIENTE")



write.table(CON_PREFERENCIA, file = "FILES/OUTPUT/09_INDICADORES_CARTERA_CON_PREFERENCIA_SEGMENTO.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)



write.table(SIN_PREFERENCIA, file = "FILES/OUTPUT/09_INDICADORES_CARTERA_SIN_PREFERENCIA_SEGMENTO.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)



write.table(DAP_FM, file = "FILES/OUTPUT/09_INDICADORES_DAP_FM_SEGMENTO.CSV", sep = ";",
            na = "", dec = ",", row.names = FALSE,
            col.names = TRUE)




